logging.level: warning

filebeat.inputs:
- type: log
  paths:
  - /app/logs/app*.log
  - /app/logs/check_list.log
  multiline:
    pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}'
    match: after
    negate: true

output.elasticsearch:
  hosts: ["${ELASTIC_URL}"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"
  protocol: "https"
  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
  pipeline: "backend-pipeline"

setup:
  ilm.enabled: true
  ilm.rollover_alias: "filebeat-%{[agent.version]}"
  setup.ilm.pattern: "{now/d}-000001"
  template.name: "filebeat-%{[agent.version]}"
  template.pattern: "filebeat-%{[agent.version]}-*"

processors:
  - add_fields:
      target: ''
      fields:
        application_name: "${ELASTIC_APPLICATION_NAME}"
        application_environment: "${ELASTIC_APPLICATION_ENVIRONMENT}"
        application_type: "${ELASTIC_APPLICATION_TYPE}"
